import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    console.log('[GENERATE-CHALLENGE] Request received');

    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    if (!LOVABLE_API_KEY) {
      throw new Error('LOVABLE_API_KEY is not set');
    }

    // Get user authentication
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      throw new Error('No authorization header');
    }

    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_ANON_KEY') ?? ''
    );

    const token = authHeader.replace('Bearer ', '');
    const { data: { user }, error: userError } = await supabaseClient.auth.getUser(token);
    
    if (userError || !user) {
      throw new Error('User not authenticated');
    }

    console.log('[GENERATE-CHALLENGE] User authenticated:', user.id);

    // Parse request body
    const { userProfile, regionalData, category, difficulty } = await req.json();
    
    console.log('[GENERATE-CHALLENGE] Input data:', { 
      userType: userProfile?.type, 
      location: userProfile?.location,
      category,
      difficulty 
    });

    // Build AI prompt based on user data
    const systemPrompt = `Te egy fenntarthatósági kihívás generátor vagy a Wellagora platformhoz.
A Wellagora mottója: "Together we thrive" - közösen építjük a pozitív környezeti hatást (handprint).

Feladatod: Generálj egy személyre szabott, konkrét fenntarthatósági kihívást a megadott adatok alapján.

FONTOS SZABÁLYOK:
- A kihívás legyen KONKRÉT, MÉRHETŐ és MEGVALÓSÍTHATÓ
- Tartalmazzon pontos lépéseket és elvárásokat
- Számold ki a várható CO2 megtakarítást (kg-ban)
- A kihívás legyen releváns a felhasználó profiljához és lokációjához
- Használj motiváló, pozitív nyelvezetet
- A handprint építés legyen a fókusz, nem a bűntudat`;

    const userPrompt = `Generálj egy fenntarthatósági kihívást az alábbi paraméterek alapján:

FELHASZNÁLÓI PROFIL:
- Típus: ${userProfile?.type || 'citizen'}
- Lokáció: ${userProfile?.location?.city || 'Budapest'}, ${userProfile?.location?.region || 'Magyarország'}
- Érdeklődési területek: ${userProfile?.interests?.join(', ') || 'általános fenntarthatóság'}
- Szint: ${userProfile?.skillLevel || 'kezdő'}

REGIONÁLIS KONTEXTUS:
- Időjárás: ${regionalData?.climate || 'mérsékelt'}
- Infrastruktúra: ${regionalData?.infrastructure || 'városi'}
- Helyi problémák: ${regionalData?.localIssues?.join(', ') || 'nincs megadva'}

KIHÍVÁS PARAMÉTEREI:
- Kategória: ${category || 'bármilyen'}
- Nehézség: ${difficulty || 'kezdő'}

Formázd a választ JSON objektumként az alábbi struktúrában:
{
  "title": "Rövid, figyelemfelkeltő cím",
  "description": "1-2 mondatos leírás",
  "longDescription": "Részletes leírás (2-3 bekezdés) a kihívásról és annak jelentőségéről",
  "category": "energy|transport|food|waste|community|innovation|water|biodiversity|circular-economy|green-finance",
  "difficulty": "beginner|intermediate|advanced|expert",
  "duration": "N nap/hét",
  "pointsReward": 100-1000,
  "steps": [
    "1. lépés konkrét leírással",
    "2. lépés konkrét leírással",
    "..."
  ],
  "tips": [
    "Hasznos tipp 1",
    "Hasznos tipp 2",
    "..."
  ],
  "impact": {
    "co2Saved": X.X,
    "description": "Magyarázat a számításról"
  },
  "validation": {
    "type": "manual|photo|api_verified",
    "description": "Hogyan kell validálni a teljesítést"
  }
}`;

    console.log('[GENERATE-CHALLENGE] Calling Lovable AI...');

    // Call Lovable AI with Gemini Flash
    const aiResponse = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${LOVABLE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ],
        temperature: 0.8,
        max_tokens: 2000
      })
    });

    if (!aiResponse.ok) {
      const errorText = await aiResponse.text();
      console.error('[GENERATE-CHALLENGE] AI API error:', aiResponse.status, errorText);
      throw new Error(`AI API error: ${aiResponse.status}`);
    }

    const aiData = await aiResponse.json();
    console.log('[GENERATE-CHALLENGE] AI response received');

    const generatedContent = aiData.choices?.[0]?.message?.content;
    if (!generatedContent) {
      throw new Error('No content generated by AI');
    }

    // Parse AI response (remove markdown code blocks if present)
    let challengeData;
    try {
      const cleanContent = generatedContent
        .replace(/```json\n?/g, '')
        .replace(/```\n?/g, '')
        .trim();
      challengeData = JSON.parse(cleanContent);
    } catch (parseError) {
      console.error('[GENERATE-CHALLENGE] JSON parse error:', parseError);
      throw new Error('Failed to parse AI response as JSON');
    }

    // Store in challenge_definitions table for admin moderation
    const { data: insertedChallenge, error: insertError } = await supabaseClient
      .from('challenge_definitions')
      .insert({
        id: `ai-${Date.now()}-${Math.random().toString(36).substring(7)}`,
        title: challengeData.title,
        description: challengeData.description,
        category: challengeData.category,
        difficulty: challengeData.difficulty,
        duration_days: parseInt(challengeData.duration.match(/\d+/)?.[0] || '7'),
        points_base: challengeData.pointsReward,
        base_impact: {
          co2_saved: challengeData.impact.co2Saved,
          description: challengeData.impact.description
        },
        validation_requirements: {
          type: challengeData.validation.type,
          description: challengeData.validation.description,
          steps: challengeData.steps,
          tips: challengeData.tips
        },
        is_active: false // Requires admin approval
      })
      .select()
      .single();

    if (insertError) {
      console.error('[GENERATE-CHALLENGE] Insert error:', insertError);
      throw insertError;
    }

    console.log('[GENERATE-CHALLENGE] Challenge stored for moderation:', insertedChallenge.id);

    return new Response(JSON.stringify({
      success: true,
      challenge: {
        ...challengeData,
        id: insertedChallenge.id,
        status: 'pending_moderation',
        message: 'Kihívás sikeresen generálva! Admin jóváhagyásra vár.'
      }
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 200,
    });

  } catch (error) {
    console.error('[GENERATE-CHALLENGE] Error:', error);
    return new Response(JSON.stringify({ 
      error: error instanceof Error ? error.message : 'Unknown error',
      details: error instanceof Error ? error.stack : undefined
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
