-- Add the remaining Káli medence programs
INSERT INTO challenge_definitions (
  id, 
  title, 
  description, 
  category, 
  difficulty, 
  points_base, 
  duration_days,
  is_active,
  is_continuous,
  project_id,
  base_impact,
  validation_requirements
) VALUES 
(
  'mestersegek-ejszakaja',
  'Mesterségek éjszakája',
  'Helyi mesteremberek tanítanak (pl. kosárfonás, fafarágás)',
  'Közösség',
  'beginner',
  200,
  1,
  true,
  false,
  '0ad8a5ec-de14-4e90-8dff-31019c535b32',
  '{"co2_saved": 0, "description": "Hagyományos mesterségek"}',
  '{"type": "manual", "description": "Részvétel igazolása", "steps": ["Részvétel a tanításon"], "tips": ["Készülj fel tanulásra"]}'
),
(
  'kali-tortenetek-tuz',
  'Káli történetek tűz mellett',
  'Téli estéken közös tűzrakás és történetmesélés',
  'Közösség',
  'beginner',
  130,
  1,
  true,
  false,
  '0ad8a5ec-de14-4e90-8dff-31019c535b32',
  '{"co2_saved": 0, "description": "Közösségi mesélés"}',
  '{"type": "manual", "description": "Részvétel és mesélés", "steps": ["Részvétel a tűzrakáson", "Történet megosztása"], "tips": ["Hozz meleg ruhát"]}'
),
(
  'szezonalis-unnepek',
  'Szezonális ünnepek',
  'Közös szüret, almaszedés, karácsonyi készülődés',
  'Közösség',
  'beginner',
  170,
  1,
  true,
  false,
  '0ad8a5ec-de14-4e90-8dff-31019c535b32',
  '{"co2_saved": 2, "description": "Szezonális ünnepek"}',
  '{"type": "manual", "description": "Részvétel az ünnepen", "steps": ["Részvétel", "Közös munka"], "tips": ["Élvezd az ünnepet"]}'
),
(
  'kali-csere-bere',
  'Káli csere-bere piac',
  'Havi cserepartik (ruha, könyv, növény...)',
  'Közösség',
  'beginner',
  140,
  30,
  true,
  false,
  '0ad8a5ec-de14-4e90-8dff-31019c535b32',
  '{"co2_saved": 4, "description": "Újrahasznosítás"}',
  '{"type": "manual", "description": "Részvétel a cserén", "steps": ["Tárgyak felajánlása", "Csere"], "tips": ["Hozz cserélhető dolgokat"]}'
),
(
  'idobank-szolgaltatasok',
  'Időbank - Szolgáltatások cseréje',
  'A közösségi tagok szolgáltatásaikat cserélik pénz helyett',
  'Közösség',
  'intermediate',
  190,
  1,
  true,
  true,
  '0ad8a5ec-de14-4e90-8dff-31019c535b32',
  '{"co2_saved": 1, "description": "Időbankrendszer"}',
  '{"type": "manual", "description": "Szolgáltatás csere", "steps": ["Szolgáltatás felajánlása", "Csere végrehajtása"], "tips": ["Egyezz időben"]}'
);